### PR TITLE
Upgrade typedoc and typescript, refactor plugin to work with typedoc 0.22.0+

### LINKED ISSUE #18: Plugin typedoc-plugin-sourcefile-url could not be loaded
typedoc 0.22.3
typedoc-plugin-sourcefile-url 1.0.6

```
Error: The plugin .../node_modules/typedoc-plugin-sourcefile-url could not be loaded.
Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/utils/component' is not defined by "exports" in .../node_modules/typedoc/package.json
```

### PR DESCRIPTION
**Pull request by nlfurniss**
Fixes #18

### CODE REVIEW

**Comment by mjvmroz** [comment]
This is the second time in two days that I've started working on a fix for a tool I'm using only to find that someone has already done it and raised a PR in the past 24 hours. Thanks for making me feel good about the world 😍

**Comment by nlfurniss** [comment]
@gdelmas when you have some time can you review?

**Comment by ToxesFoxes** [comment]
How soon will it be fixed? Without this plugin you can't add source links😄

**Comment by nlfurniss** [comment]
> How soon will it be fixed? Without this plugin you can't add source links😄

I don’t think this will ever be merged and released, so I forked the repo with the changes. 

https://github.com/nlfurniss/typedoc-plugin-sourcefile-url

**Comment by gdelmas** [comment]
as i am no longer using this plugin myself, and am quite limited on time, i would be happy for somebody to take over maintenance.  have you published updated versions to npm? happy to look into how to transfer the ownership, if you are willing to maintain the plugin.

**Comment by nlfurniss** [comment]
> as i am no longer using this plugin myself, and am quite limited on time, i would be happy for somebody to take over maintenance. have you published updated versions to npm? happy to look into how to transfer the ownership, if you are willing to maintain the plugin.

Sure would be happy to. I published my fork to NPM

**Comment by ThisIsMissEm** [comment]
@nlfurniss looks like the plugin is broken again as of typedoc `0.23.2` due to:
> Removed ProjectReflection.files, this was an internal cache that should not have been exposed, and shouldn't have existed in the first place, since removing it made TypeDoc faster.

I'm not sure how to resolve that?

**Pull request closed without merging**
